modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="reds_weapons"
version="1.0.0"
displayName="Red's Weapons"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="JD, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.reds_weapons]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



